name: stackoverflow_case

profile: stackoverflow_case

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stackoverflow_case:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    # intermediate:
    #   +materialized: view
    # marts:
    #   +materialized: table  # maybe use view instead to save costs
